
CREATE TABLE IF NOT EXISTS MEMBER(
    Id BIGINT,
    username VARCHAR,
    isbot BOOLEAN,
    PRIMARY KEY(Id)
);
CREATE TABLE IF NOT EXISTS GUILD(
    Id BIGINT,
    name VARCHAR,
    limits INT DEFAULT 3,
    banpenalty INT DEFAULT 1,
    PRIMARY KEY(Id)
);
CREATE TABLE IF NOT EXISTS BLACKLIST(
    guildId BIGINT,
    term VARCHAR,
    PRIMARY KEY(term,guildId),
    CONSTRAINT has FOREIGN KEY(guildId) REFERENCES GUILD(Id)
);
CREATE TABLE IF NOT EXISTS MEMBERSHIP(
    memberId BIGINT,
    guildId BIGINT,
    infrigement INT DEFAULT 0,
    PRIMARY KEY(memberId, guildId),
    CONSTRAINT joins FOREIGN KEY(memberId) REFERENCES MEMBER(Id),
    CONSTRAINT tracks FOREIGN KEY(guildId) REFERENCES GUILD(Id)
);

